terraform {
  required_version = ">= 1.9, < 2.0"
}
variable "region" { type = string }
variable "home_region" { type = string }
variable "inventory" {
  description = "Read-only account inventory generated by scripts/oci-preflight.py."
  type = object({
    verified_at             = string
    region                  = string
    tenancy_id              = string
    always_free_only        = bool
    existing_a1_ocpus       = number
    existing_a1_memory_gb   = number
    existing_storage_gb     = number
    existing_volume_backups = number
    paid_resources_reviewed = bool
    observed_a1_ocpus       = number
    observed_a1_memory_gb   = number
    observed_storage_gb     = number
    managed_a1_ocpus        = number
    managed_a1_memory_gb    = number
    managed_storage_gb      = number
    managed_instance_ids    = list(string)
    managed_data_volume_ids = list(string)
    managed_boot_volume_ids = list(string)
    terraform_state_sha256  = string
  })
}
variable "tenancy_id" { type = string }
resource "terraform_data" "verified" {
  input = var.inventory
  lifecycle {
    precondition {
      condition     = var.region == var.home_region && var.region == var.inventory.region && var.tenancy_id == var.inventory.tenancy_id
      error_message = "Deployment must use the inventoried tenancy home region."
    }
    precondition {
      condition     = var.inventory.always_free_only && var.inventory.paid_resources_reviewed
      error_message = "Always-Free-only account and eligibility review are mandatory; no trial credits or paid fallback."
    }
    precondition {
      condition     = timecmp(var.inventory.verified_at, timestamp()) <= 0 && timecmp(timeadd(var.inventory.verified_at, "1h"), timestamp()) > 0
      error_message = "Inventory must be generated in the last hour. Refresh before applying."
    }
    precondition {
      condition = (
        var.inventory.existing_a1_ocpus >= 0 && var.inventory.existing_a1_memory_gb >= 0 && var.inventory.existing_storage_gb >= 0 &&
        var.inventory.managed_a1_ocpus >= 0 && var.inventory.managed_a1_ocpus <= 2 &&
        var.inventory.managed_a1_memory_gb >= 0 && var.inventory.managed_a1_memory_gb <= 12 &&
        var.inventory.managed_storage_gb >= 0 && var.inventory.managed_storage_gb <= 100 &&
        var.inventory.observed_a1_ocpus == var.inventory.existing_a1_ocpus + var.inventory.managed_a1_ocpus &&
        var.inventory.observed_a1_memory_gb == var.inventory.existing_a1_memory_gb + var.inventory.managed_a1_memory_gb &&
        var.inventory.observed_storage_gb == var.inventory.existing_storage_gb + var.inventory.managed_storage_gb &&
        var.inventory.observed_a1_ocpus <= 2 && var.inventory.observed_a1_memory_gb <= 12 && var.inventory.observed_storage_gb <= 200
      )
      error_message = "Observed account totals and state-verified Hydra exclusions must reconcile inside the free allocation."
    }
    precondition {
      condition = (
        length(var.inventory.managed_instance_ids) <= 1 && length(var.inventory.managed_data_volume_ids) <= 1 &&
        length(var.inventory.managed_boot_volume_ids) <= length(var.inventory.managed_instance_ids) &&
        (length(var.inventory.managed_instance_ids) + length(var.inventory.managed_data_volume_ids) == 0 ||
        can(regex("^[a-f0-9]{64}$", var.inventory.terraform_state_sha256))) &&
        (var.inventory.managed_a1_ocpus == 0 || length(var.inventory.managed_instance_ids) == 1) &&
        (var.inventory.managed_storage_gb == 0 || length(var.inventory.managed_data_volume_ids) + length(var.inventory.managed_boot_volume_ids) > 0)
      )
      error_message = "Managed exclusions require exact Terraform state IDs, bounded resource counts, and the state export digest."
    }
    precondition {
      condition     = var.inventory.existing_a1_ocpus + 2 <= 2 && var.inventory.existing_a1_memory_gb + 12 <= 12
      error_message = "Hydra would exceed the current 2 OCPU / 12 GB account-wide A1 free allowance."
    }
    precondition {
      condition     = var.inventory.existing_storage_gb + 100 <= 200 && var.inventory.existing_volume_backups <= 5
      error_message = "Hydra would exceed account-wide free block/boot storage or backup allowances."
    }
  }
}
output "verified" { value = terraform_data.verified.id }
