terraform {
  required_version = ">= 1.9, < 2.0"
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 9.8.0"
    }
  }
}

variable "region" { type = string }
variable "tenancy_id" { type = string }
variable "compartment_id" { type = string }
variable "availability_domain" { type = string }
variable "ssh_public_key" { type = string }
variable "admin_cidr" { type = string }
variable "inventory_path" {
  type        = string
  description = "Fresh inventory JSON generated by scripts/oci-preflight.py, stored outside Git."
}
provider "oci" {
  region              = var.region
  config_file_profile = "DEFAULT"
}
data "oci_identity_region_subscriptions" "account" { tenancy_id = var.tenancy_id }
locals {
  home_region = one([for r in data.oci_identity_region_subscriptions.account.region_subscriptions : r.region_name if r.is_home_region])
}
module "guardrails" {
  source      = "../../modules/zero-cost-guardrails"
  region      = var.region
  home_region = local.home_region
  tenancy_id  = var.tenancy_id
  inventory   = jsondecode(file(var.inventory_path))
}
module "runtime" {
  source              = "../../modules/oracle-arm"
  compartment_id      = var.compartment_id
  tenancy_id          = var.tenancy_id
  availability_domain = var.availability_domain
  ssh_public_key      = var.ssh_public_key
  admin_cidr          = var.admin_cidr
  depends_on          = [module.guardrails]
}
output "public_ip" { value = module.runtime.public_ip }
output "instance_id" { value = module.runtime.instance_id }
