export const locales = ["es", "en", "pt", "ar"] as const;
export type Locale = typeof locales[number];
export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
export const languageNames: Record<Locale, string> = { es: "Español", en: "English", pt: "Português", ar: "العربية" };

const es = {
  budgetUnavailable: "Espera a que haya al menos dos pods disponibles y ninguno pendiente antes de inyectar caos.",
  tapestryKicker: "BASTIDOR DEL LABORATORIO", tapestryTitle: "Pods, punto a punto", tapestryBody: "Pods actuales y huellas reales de tus experimentos.",
  tapestryReady: "Disponible", tapestryUnready: "No disponible", tapestryDeleted: "Eliminación confirmada", tapestryHistory: "Huella histórica", tapestryCurrent: "Pod actual", tapestryMended: "Recuperación registrada",
  tapestrySelect: "Seleccionar pod {name}", tapestryPan: "Mapa de pods. Usa Tab para elegir un pod y las flechas para desplazarte.", tapestryLastKnown: "Último estado conocido", tapestryLegend: "Leyenda del bastidor", tapestryEmpty: "Aún no hay pods observados.",
  tapestryCaption: "Cada parche es un pod. Las costuras organizan la vista.", tapestryRecoveryScope: "El experimento registró una recuperación; la huella conserva el pod eliminado y no identifica su reemplazo.", tapestryUpdated: "Estado de los pods actualizado.",
  dryRunCompleted: "Simulación completada. Se validó el objetivo sin eliminar el pod.",
  experimentRecovered: "Experimento completado. El agente confirmó la recuperación del laboratorio.",
  experimentFailed: "El experimento terminó con un fallo. Revisa el detalle del historial.",
  eventGap: "La retención de eventos venció. El historial y los objetivos se actualizaron desde la API.",
  eventZero: "eventos", eventTwo: "eventos", eventFew: "eventos", eventMany: "eventos",
  skip: "Ir al contenido", title: "La resiliencia se demuestra.", titleAccent: "Provoca. Observa. Aprende.",
  eyebrow: "LABORATORIO DE CHAOS ENGINEERING", subtitle: "Corta una cabeza y dos más tomarán su lugar. Experimenta con fallos controlados y observa cómo Kubernetes recupera tu sistema.",
  console: "Consola", history: "Historial", architecture: "Arquitectura", language: "Idioma", signIn: "Entrar con GitHub", signOut: "Salir", operator: "Operador", reader: "Observador", local: "Sesión local", account: "Cuenta",
  loading: "Conectando", live: "En vivo", polling: "Consulta periódica", offline: "Sin conexión", reconnecting: "Reconectando",
  offlineTitle: "El plano de control no está disponible", offlineBody: "Esperando una conexión con Hydra API. Los experimentos permanecerán deshabilitados hasta recibir el estado del clúster.", retry: "Reintentar", errorTitle: "No se pudo completar la operación", stale: "Datos pendientes de actualizar. Los experimentos están deshabilitados.",
  scope: "Ámbito autorizado", replicas: "Réplicas disponibles", scopeHint: "Solo pods del laboratorio", replicaHint: "Estado consultado en Kubernetes", noData: "Sin datos", transport: "Canal de telemetría", websocket: "WebSocket · SignalR", pollingHint: "Eventos recuperados por HTTP", offlineHint: "Esperando API", lastUpdate: "Última actualización",
  experimentTitle: "Inyectar un fallo", experimentKicker: "01 / EXPERIMENTO CONTROLADO", experimentBody: "Un pod autorizado. Una interrupción. Evidencia para tu siguiente decisión.", target: "Pod objetivo", chooseTarget: "Selecciona un pod", noTargets: "No hay pods autorizados", targetHint: "El UID se verifica antes de eliminar. Si el pod cambió, el experimento se rechaza.", mode: "Modo de ejecución", dryRun: "Simulación", dryRunHint: "Valida permisos y objetivo. No elimina el pod.", destructive: "Eliminar un pod", destructiveHint: "Kubernetes recibirá una solicitud real de eliminación.", inject: "INJECT CHAOS", simulate: "VALIDAR EXPERIMENTO", submitting: "Enviando…", signInHint: "Inicia sesión como operador para ejecutar experimentos.", observerHint: "Tu cuenta tiene acceso de lectura. Se necesita permiso de operador.", localHint: "Modo local de desarrollo. El acceso público requiere GitHub OAuth.", confirmTitle: "Confirmar eliminación", confirmBody: "Se eliminará un pod del laboratorio. La recuperación depende del clúster y se medirá con eventos reales.", confirm: "ELIMINAR POD", cancel: "Cancelar", queued: "Experimento recibido. Esperando el agente.", pending: "Hay un experimento en curso. Espera su resultado.", uncertain: "No se pudo confirmar la recepción. Reintenta con la misma solicitud para evitar duplicados.", resetDraft: "Descartar solicitud pendiente",
  activityTitle: "La evidencia del fallo", activityKicker: "02 / HISTORIAL DE EXPERIMENTOS", activityBody: "Cada experimento conserva su objetivo, resultado y tiempo de recuperación.", emptyTitle: "Tu primer experimento empieza aquí", emptyBody: "Cuando el agente procese una solicitud, aparecerán aquí sus eventos. No hay ejecuciones de muestra.", experiment: "Experimento", recovery: "Recuperación", timeline: "Eventos recientes", emptyEvents: "Los eventos reales aparecerán después de conectar la API.", simulated: "Simulación", statusQueued: "En cola", statusRunning: "En curso", statusRecovered: "Recuperado", statusCompleted: "Completado", statusFailed: "Falló", statusRejected: "Rechazado", statusUnknown: "Estado", tweet: "Borrador para X", copy: "Copiar", copied: "Copiado", copyError: "No se pudo copiar. Selecciona el texto del borrador.",
  architectureTitle: "Diseñada para un presupuesto de $0", architectureKicker: "03 / INFRAESTRUCTURA PROPIA", architectureBody: "Un clúster ligero, componentes portables y un radio de impacto explícito.", controlPlane: "Plano de control protegido", controlDesc: "API, interfaz, agente y PostgreSQL viven fuera del namespace de pruebas.", demo: "Laboratorio aislado", demoDesc: "RBAC limita las eliminaciones al namespace autorizado. ReplicaSets reponen las réplicas declaradas.", resources: "Política de recursos", resourceDesc: "Requests y limits configurados en Kubernetes. El consumo real debe medirse en tu despliegue.", resourceNote: "amd64 + arm64 · HPA acotado · probes de salud", home: "En tu casa", homeDesc: "k3s sobre tu equipo existente. Cloudflare Tunnel para publicar con un dominio disponible.", oracle: "Oracle Always Free", oracleDesc: "k3s sobre ARM dentro de la cuota de tu cuenta y sujeto a disponibilidad de capacidad.", costNote: "$0 en servicios obligatorios. El equipo, la electricidad y un dominio pueden tener costo. Una sola máquina conserva un punto de fallo.", footer: "Chaos Engineering, con límites claros.", openSource: "Open Source · Apache-2.0", safety: "El control de Hydra nunca es un objetivo.", readyOne: "pod disponible", readyOther: "pods disponibles", eventOne: "evento", eventOther: "eventos", retryError: "No fue posible consultar el clúster.", unauthorized: "La sesión expiró. Inicia sesión de nuevo.", forbidden: "Tu sesión no tiene permiso para esta operación.", conflict: "El objetivo cambió o el clúster ya tiene un experimento en curso. Actualiza y revisa el pod.", rateLimited: "Se alcanzó el límite de solicitudes. Espera y vuelve a intentarlo.", serverError: "La API no pudo procesar la solicitud. Revisa su estado e inténtalo de nuevo.", invalidResponse: "La API devolvió una respuesta inesperada.", unknownError: "La conexión se interrumpió. Comprueba el estado del servicio.",
};
export type Messages = { [Key in keyof typeof es]: string };
const en: Messages = {
  budgetUnavailable: "Wait until at least two pods are available and none are pending before injecting chaos.",
  tapestryKicker: "LABORATORY HOOP", tapestryTitle: "Pods, stitch by stitch", tapestryBody: "Current pods and real traces of your experiments.",
  tapestryReady: "Available", tapestryUnready: "Unavailable", tapestryDeleted: "Deletion confirmed", tapestryHistory: "Historical trace", tapestryCurrent: "Current pod", tapestryMended: "Recovery recorded",
  tapestrySelect: "Select pod {name}", tapestryPan: "Pod map. Use Tab to choose a pod and arrow keys to scroll.", tapestryLastKnown: "Last known state", tapestryLegend: "Hoop legend", tapestryEmpty: "No pods have been observed yet.",
  tapestryCaption: "Each patch represents a pod. The stitches organize the view.", tapestryRecoveryScope: "The experiment recorded a recovery; the trace preserves the deleted pod without identifying its replacement.", tapestryUpdated: "Pod state updated.",
  dryRunCompleted: "Dry run completed. The target was validated without deleting the pod.",
  experimentRecovered: "Experiment completed. The agent confirmed recovery of the lab.",
  experimentFailed: "The experiment ended in failure. Review the history for details.",
  eventGap: "Event retention expired. History and targets were refreshed from the API.",
  eventZero: "events", eventTwo: "events", eventFew: "events", eventMany: "events",
  skip: "Skip to content", title: "Resilience is proven.", titleAccent: "Disrupt. Observe. Learn.", eyebrow: "CHAOS ENGINEERING LAB", subtitle: "Cut off one head and two more will take its place. Run controlled failure experiments and watch Kubernetes recover your system.",
  console: "Console", history: "History", architecture: "Architecture", language: "Language", signIn: "Sign in with GitHub", signOut: "Sign out", operator: "Operator", reader: "Observer", local: "Local session", account: "Account", loading: "Connecting", live: "Live", polling: "Polling", offline: "Disconnected", reconnecting: "Reconnecting",
  offlineTitle: "The control plane is unavailable", offlineBody: "Waiting for a connection to Hydra API. Experiments stay disabled until cluster state is available.", retry: "Retry", errorTitle: "The operation could not be completed", stale: "Waiting for refreshed data. Experiments are disabled.",
  scope: "Authorized scope", replicas: "Available replicas", scopeHint: "Lab pods only", replicaHint: "State reported by Kubernetes", noData: "No data", transport: "Telemetry channel", websocket: "WebSocket · SignalR", pollingHint: "Events recovered over HTTP", offlineHint: "Waiting for API", lastUpdate: "Last updated",
  experimentTitle: "Inject a failure", experimentKicker: "01 / CONTROLLED EXPERIMENT", experimentBody: "One authorized pod. One disruption. Evidence for your next decision.", target: "Target pod", chooseTarget: "Select a pod", noTargets: "No authorized pods", targetHint: "The UID is checked before deletion. A changed pod causes the experiment to be rejected.", mode: "Execution mode", dryRun: "Dry run", dryRunHint: "Validate permissions and target. No pod is deleted.", destructive: "Delete one pod", destructiveHint: "Kubernetes will receive an actual deletion request.", inject: "INJECT CHAOS", simulate: "VALIDATE EXPERIMENT", submitting: "Submitting…", signInHint: "Sign in as an operator to run experiments.", observerHint: "Your account has read access. Operator permissions are required.", localHint: "Local development mode. Public access requires GitHub OAuth.", confirmTitle: "Confirm deletion", confirmBody: "One lab pod will be deleted. Recovery depends on the cluster and will be measured from real events.", confirm: "DELETE POD", cancel: "Cancel", queued: "Experiment received. Waiting for the agent.", pending: "An experiment is in progress. Wait for its result.", uncertain: "Receipt could not be confirmed. Retry the same request to avoid duplicates.", resetDraft: "Discard pending request",
  activityTitle: "Evidence of the failure", activityKicker: "02 / EXPERIMENT HISTORY", activityBody: "Every experiment preserves its target, outcome and recovery time.", emptyTitle: "Your first experiment starts here", emptyBody: "Events appear when the agent processes a request. There are no sample runs.", experiment: "Experiment", recovery: "Recovery", timeline: "Recent events", emptyEvents: "Real events will appear after connecting the API.", simulated: "Dry run", statusQueued: "Queued", statusRunning: "Running", statusRecovered: "Recovered", statusCompleted: "Completed", statusFailed: "Failed", statusRejected: "Rejected", statusUnknown: "Status", tweet: "Draft for X", copy: "Copy", copied: "Copied", copyError: "Could not copy. Select the draft text.",
  architectureTitle: "Designed for a $0 budget", architectureKicker: "03 / YOUR INFRASTRUCTURE", architectureBody: "A lightweight cluster, portable components and an explicit blast radius.", controlPlane: "Protected control plane", controlDesc: "API, interface, agent and PostgreSQL stay outside the test namespace.", demo: "Isolated lab", demoDesc: "RBAC limits deletions to the authorized namespace. ReplicaSets restore the declared replicas.", resources: "Resource policy", resourceDesc: "Requests and limits configured in Kubernetes. Actual consumption needs measuring on your deployment.", resourceNote: "amd64 + arm64 · bounded HPA · health probes", home: "At home", homeDesc: "k3s on your existing hardware. Cloudflare Tunnel for publishing with an available domain.", oracle: "Oracle Always Free", oracleDesc: "k3s on ARM within your account quota and subject to capacity availability.", costNote: "$0 in required services. Hardware, electricity and a domain can have costs. A single machine remains a failure point.", footer: "Chaos Engineering, with clear boundaries.", openSource: "Open Source · Apache-2.0", safety: "Hydra's control plane is never a target.", readyOne: "pod available", readyOther: "pods available", eventOne: "event", eventOther: "events", retryError: "Could not query the cluster.", unauthorized: "Your session expired. Sign in again.", forbidden: "Your session does not have permission for this operation.", conflict: "The target changed or an experiment is already running. Refresh and review the pod.", rateLimited: "Request limit reached. Wait and try again.", serverError: "The API could not process the request. Check its health and retry.", invalidResponse: "The API returned an unexpected response.", unknownError: "The connection was interrupted. Check the service status.",
};
const pt: Messages = {
  budgetUnavailable: "Espere até haver pelo menos dois pods disponíveis e nenhum pendente antes de injetar caos.",
  tapestryKicker: "BASTIDOR DO LABORATÓRIO", tapestryTitle: "Pods, ponto a ponto", tapestryBody: "Pods atuais e vestígios reais dos seus experimentos.",
  tapestryReady: "Disponível", tapestryUnready: "Indisponível", tapestryDeleted: "Exclusão confirmada", tapestryHistory: "Vestígio histórico", tapestryCurrent: "Pod atual", tapestryMended: "Recuperação registrada",
  tapestrySelect: "Selecionar pod {name}", tapestryPan: "Mapa de pods. Use Tab para escolher um pod e as setas para navegar.", tapestryLastKnown: "Último estado conhecido", tapestryLegend: "Legenda do bastidor", tapestryEmpty: "Ainda não há pods observados.",
  tapestryCaption: "Cada retalho representa um pod. As costuras organizam a vista.", tapestryRecoveryScope: "O experimento registrou uma recuperação; o vestígio preserva o pod excluído sem identificar seu substituto.", tapestryUpdated: "Estado dos pods atualizado.",
  dryRunCompleted: "Simulação concluída. O alvo foi validado sem excluir o pod.",
  experimentRecovered: "Experimento concluído. O agente confirmou a recuperação do laboratório.",
  experimentFailed: "O experimento terminou com uma falha. Confira os detalhes no histórico.",
  eventGap: "A retenção de eventos expirou. O histórico e os alvos foram atualizados pela API.",
  eventZero: "eventos", eventTwo: "eventos", eventFew: "eventos", eventMany: "eventos",
  skip: "Ir ao conteúdo", title: "Resiliência se demonstra.", titleAccent: "Provoque. Observe. Aprenda.", eyebrow: "LABORATÓRIO DE CHAOS ENGINEERING", subtitle: "Corte uma cabeça e duas tomarão seu lugar. Experimente falhas controladas e observe como o Kubernetes recupera seu sistema.",
  console: "Console", history: "Histórico", architecture: "Arquitetura", language: "Idioma", signIn: "Entrar com GitHub", signOut: "Sair", operator: "Operador", reader: "Observador", local: "Sessão local", account: "Conta", loading: "Conectando", live: "Ao vivo", polling: "Consulta periódica", offline: "Sem conexão", reconnecting: "Reconectando",
  offlineTitle: "O plano de controle está indisponível", offlineBody: "Aguardando conexão com a Hydra API. Os experimentos ficam desativados até receber o estado do cluster.", retry: "Tentar novamente", errorTitle: "Não foi possível concluir a operação", stale: "Aguardando dados atualizados. Experimentos desativados.", scope: "Escopo autorizado", replicas: "Réplicas disponíveis", scopeHint: "Apenas pods do laboratório", replicaHint: "Estado consultado no Kubernetes", noData: "Sem dados", transport: "Canal de telemetria", websocket: "WebSocket · SignalR", pollingHint: "Eventos recuperados por HTTP", offlineHint: "Aguardando API", lastUpdate: "Última atualização",
  experimentTitle: "Injetar uma falha", experimentKicker: "01 / EXPERIMENTO CONTROLADO", experimentBody: "Um pod autorizado. Uma interrupção. Evidência para sua próxima decisão.", target: "Pod alvo", chooseTarget: "Selecione um pod", noTargets: "Não há pods autorizados", targetHint: "O UID é verificado antes da exclusão. Se o pod mudou, o experimento é rejeitado.", mode: "Modo de execução", dryRun: "Simulação", dryRunHint: "Valida permissões e alvo. Não exclui o pod.", destructive: "Excluir um pod", destructiveHint: "O Kubernetes receberá uma solicitação real de exclusão.", inject: "INJECT CHAOS", simulate: "VALIDAR EXPERIMENTO", submitting: "Enviando…", signInHint: "Entre como operador para executar experimentos.", observerHint: "Sua conta tem acesso de leitura. É necessária permissão de operador.", localHint: "Modo local de desenvolvimento. Acesso público exige GitHub OAuth.", confirmTitle: "Confirmar exclusão", confirmBody: "Um pod do laboratório será excluído. A recuperação depende do cluster e será medida com eventos reais.", confirm: "EXCLUIR POD", cancel: "Cancelar", queued: "Experimento recebido. Aguardando o agente.", pending: "Há um experimento em andamento. Aguarde seu resultado.", uncertain: "Não foi possível confirmar o recebimento. Repita a mesma solicitação para evitar duplicatas.", resetDraft: "Descartar solicitação pendente",
  activityTitle: "A evidência da falha", activityKicker: "02 / HISTÓRICO DE EXPERIMENTOS", activityBody: "Cada experimento preserva seu alvo, resultado e tempo de recuperação.", emptyTitle: "Seu primeiro experimento começa aqui", emptyBody: "Os eventos aparecem quando o agente processa uma solicitação. Não há execuções de exemplo.", experiment: "Experimento", recovery: "Recuperação", timeline: "Eventos recentes", emptyEvents: "Eventos reais aparecerão após conectar a API.", simulated: "Simulação", statusQueued: "Na fila", statusRunning: "Em andamento", statusRecovered: "Recuperado", statusCompleted: "Concluído", statusFailed: "Falhou", statusRejected: "Rejeitado", statusUnknown: "Estado", tweet: "Rascunho para X", copy: "Copiar", copied: "Copiado", copyError: "Não foi possível copiar. Selecione o texto do rascunho.",
  architectureTitle: "Projetada para um orçamento de $0", architectureKicker: "03 / INFRAESTRUTURA PRÓPRIA", architectureBody: "Um cluster leve, componentes portáveis e um raio de impacto explícito.", controlPlane: "Plano de controle protegido", controlDesc: "API, interface, agente e PostgreSQL ficam fora do namespace de testes.", demo: "Laboratório isolado", demoDesc: "RBAC limita exclusões ao namespace autorizado. ReplicaSets restauram as réplicas declaradas.", resources: "Política de recursos", resourceDesc: "Requests e limits configurados no Kubernetes. O consumo real precisa ser medido no seu ambiente.", resourceNote: "amd64 + arm64 · HPA limitado · probes de saúde", home: "Na sua casa", homeDesc: "k3s no equipamento existente. Cloudflare Tunnel para publicar com um domínio disponível.", oracle: "Oracle Always Free", oracleDesc: "k3s em ARM dentro da cota da conta e sujeito à disponibilidade de capacidade.", costNote: "$0 em serviços obrigatórios. Equipamento, eletricidade e domínio podem ter custo. Uma única máquina continua sendo um ponto de falha.", footer: "Chaos Engineering, com limites claros.", openSource: "Open Source · Apache-2.0", safety: "O controle da Hydra nunca é um alvo.", readyOne: "pod disponível", readyOther: "pods disponíveis", eventOne: "evento", eventOther: "eventos", retryError: "Não foi possível consultar o cluster.", unauthorized: "Sua sessão expirou. Entre novamente.", forbidden: "Sua sessão não tem permissão para esta operação.", conflict: "O alvo mudou ou já há um experimento em andamento. Atualize e confira o pod.", rateLimited: "Limite de solicitações atingido. Aguarde e tente novamente.", serverError: "A API não conseguiu processar a solicitação. Verifique seu estado e tente novamente.", invalidResponse: "A API retornou uma resposta inesperada.", unknownError: "A conexão foi interrompida. Verifique o estado do serviço.",
};
const ar: Messages = {
  budgetUnavailable: "انتظر حتى تتوفر وحدتان على الأقل ولا تبقى أي وحدة معلقة قبل حقن العطل.",
  tapestryKicker: "طارة المختبر", tapestryTitle: "وحدات، غرزة بغرزة", tapestryBody: "الوحدات الحالية والآثار الفعلية لتجاربك.",
  tapestryReady: "متاح", tapestryUnready: "غير متاح", tapestryDeleted: "الحذف مؤكد", tapestryHistory: "أثر من السجل", tapestryCurrent: "وحدة حالية", tapestryMended: "تم تسجيل التعافي",
  tapestrySelect: "اختيار الوحدة {name}", tapestryPan: "خريطة الوحدات. استخدم Tab لاختيار وحدة ومفاتيح الأسهم للتمرير.", tapestryLastKnown: "آخر حالة معروفة", tapestryLegend: "دليل الطارة", tapestryEmpty: "لم تُرصد أي وحدات بعد.",
  tapestryCaption: "تمثل كل رقعة وحدة. تنظم الغرز المشهد.", tapestryRecoveryScope: "سجلت التجربة تعافيًا؛ يحتفظ الأثر بالوحدة المحذوفة دون تحديد بديلها.", tapestryUpdated: "تم تحديث حالة الوحدات.",
  dryRunCompleted: "اكتملت المحاكاة. تم التحقق من الهدف دون حذف الوحدة.",
  experimentRecovered: "اكتملت التجربة. أكد الوكيل تعافي المختبر.",
  experimentFailed: "انتهت التجربة بفشل. راجع التفاصيل في السجل.",
  eventGap: "انتهت فترة حفظ الأحداث. تم تحديث السجل والأهداف من الواجهة.",
  eventZero: "أحداث", eventTwo: "حدثان", eventFew: "أحداث", eventMany: "حدثًا",
  skip: "انتقل إلى المحتوى", title: "المرونة تثبت بالتجربة.", titleAccent: "عطّل. راقب. تعلّم.", eyebrow: "مختبر هندسة الفوضى", subtitle: "اقطع رأسًا وسيحل محله رأسان. اختبر أعطالًا مضبوطة وراقب كيف يستعيد Kubernetes نظامك.", console: "لوحة التحكم", history: "السجل", architecture: "البنية", language: "اللغة", signIn: "الدخول عبر GitHub", signOut: "تسجيل الخروج", operator: "مشغّل", reader: "مراقب", local: "جلسة محلية", account: "الحساب", loading: "جارٍ الاتصال", live: "مباشر", polling: "استعلام دوري", offline: "غير متصل", reconnecting: "إعادة الاتصال",
  offlineTitle: "مستوى التحكم غير متاح", offlineBody: "بانتظار الاتصال بواجهة Hydra. تبقى التجارب معطلة حتى تتوفر حالة المجموعة.", retry: "إعادة المحاولة", errorTitle: "تعذر إتمام العملية", stale: "بانتظار تحديث البيانات. التجارب معطلة.", scope: "النطاق المصرح به", replicas: "النسخ المتاحة", scopeHint: "وحدات المختبر فقط", replicaHint: "حالة مستمدة من Kubernetes", noData: "لا توجد بيانات", transport: "قناة القياس", websocket: "WebSocket · SignalR", pollingHint: "استعادة الأحداث عبر HTTP", offlineHint: "بانتظار الواجهة", lastUpdate: "آخر تحديث",
  experimentTitle: "حقن عطل", experimentKicker: "01 / تجربة مضبوطة", experimentBody: "وحدة مصرح بها. عطل واحد. دليل لقرارك التالي.", target: "الوحدة المستهدفة", chooseTarget: "اختر وحدة", noTargets: "لا توجد وحدات مصرح بها", targetHint: "يُفحص UID قبل الحذف. إذا تغيرت الوحدة، تُرفض التجربة.", mode: "وضع التنفيذ", dryRun: "محاكاة", dryRunHint: "تحقق من الصلاحيات والهدف دون حذف الوحدة.", destructive: "حذف وحدة واحدة", destructiveHint: "سيتلقى Kubernetes طلب حذف فعليًا.", inject: "INJECT CHAOS", simulate: "التحقق من التجربة", submitting: "جارٍ الإرسال…", signInHint: "سجل الدخول كمشغّل لتنفيذ التجارب.", observerHint: "لديك صلاحية القراءة. التنفيذ يتطلب صلاحية المشغّل.", localHint: "وضع تطوير محلي. الوصول العام يتطلب GitHub OAuth.", confirmTitle: "تأكيد الحذف", confirmBody: "ستُحذف وحدة من المختبر. يعتمد التعافي على المجموعة وسيُقاس بالأحداث الفعلية.", confirm: "حذف الوحدة", cancel: "إلغاء", queued: "استُلمت التجربة. بانتظار الوكيل.", pending: "هناك تجربة قيد التنفيذ. انتظر نتيجتها.", uncertain: "تعذر تأكيد الاستلام. أعد الطلب نفسه لتجنب التكرار.", resetDraft: "تجاهل الطلب المعلق",
  activityTitle: "دليل العطل", activityKicker: "02 / سجل التجارب", activityBody: "تحتفظ كل تجربة بهدفها ونتيجتها ومدة التعافي.", emptyTitle: "تبدأ تجربتك الأولى هنا", emptyBody: "تظهر الأحداث عندما يعالج الوكيل الطلب. لا توجد تجارب نموذجية.", experiment: "تجربة", recovery: "التعافي", timeline: "الأحداث الأخيرة", emptyEvents: "ستظهر الأحداث الفعلية بعد الاتصال بالواجهة.", simulated: "محاكاة", statusQueued: "في الانتظار", statusRunning: "قيد التنفيذ", statusRecovered: "تم التعافي", statusCompleted: "مكتمل", statusFailed: "فشل", statusRejected: "مرفوض", statusUnknown: "الحالة", tweet: "مسودة لمنصة X", copy: "نسخ", copied: "تم النسخ", copyError: "تعذر النسخ. حدد نص المسودة.",
  architectureTitle: "مصممة لميزانية $0", architectureKicker: "03 / بنيتك الخاصة", architectureBody: "مجموعة خفيفة ومكونات قابلة للنقل ونطاق تأثير واضح.", controlPlane: "مستوى تحكم محمي", controlDesc: "تبقى الواجهة والوكيل وPostgreSQL خارج نطاق الاختبار.", demo: "مختبر معزول", demoDesc: "تحصر RBAC الحذف في النطاق المصرح به. تستعيد ReplicaSets النسخ المحددة.", resources: "سياسة الموارد", resourceDesc: "طلبات وحدود موارد مضبوطة في Kubernetes. يجب قياس الاستهلاك الفعلي في بيئتك.", resourceNote: "amd64 + arm64 · HPA محدود · فحوص صحة", home: "في منزلك", homeDesc: "k3s على أجهزتك الحالية. Cloudflare Tunnel للنشر باستخدام نطاق متاح.", oracle: "Oracle Always Free", oracleDesc: "k3s على ARM ضمن حصة حسابك ورهن توفر السعة.", costNote: "$0 للخدمات المطلوبة. قد توجد تكلفة للأجهزة والكهرباء والنطاق. تبقى الآلة الواحدة نقطة فشل.", footer: "هندسة الفوضى بحدود واضحة.", openSource: "مفتوح المصدر · Apache-2.0", safety: "مستوى تحكم Hydra ليس هدفًا أبدًا.", readyOne: "وحدة متاحة", readyOther: "وحدات متاحة", eventOne: "حدث", eventOther: "أحداث", retryError: "تعذر الاستعلام عن المجموعة.", unauthorized: "انتهت الجلسة. سجل الدخول مجددًا.", forbidden: "لا تسمح جلستك بهذه العملية.", conflict: "تغير الهدف أو هناك تجربة قيد التنفيذ. حدث البيانات وراجع الوحدة.", rateLimited: "تم بلوغ حد الطلبات. انتظر وحاول مجددًا.", serverError: "تعذر على الواجهة معالجة الطلب. تحقق من حالتها وأعد المحاولة.", invalidResponse: "أعادت الواجهة استجابة غير متوقعة.", unknownError: "انقطع الاتصال. تحقق من حالة الخدمة.",
};
export const messages: Record<Locale, Messages> = { es, en, pt, ar };
export function plural(locale: Locale, count: number, one: string, other: string, forms: Partial<Record<Intl.LDMLPluralRule, string>> = {}): string {
  const category = new Intl.PluralRules(locale).select(count);
  return `${new Intl.NumberFormat(locale).format(count)} ${forms[category] ?? (category === "one" ? one : other)}`;
}
